### ISSUE TITLE
Template Error: Encountered unsupported function: fn::lower Supported 

### ISSUE THREAD

**Issue by lxandrexl** [icarus-sullivan/serverless-plugin-utils#8]
Serverless error in framework version 3. Help pls

**Comment by icarus-sullivan** [comment]
Framework 3 includes a new way of resolving template defined values. From what I've read and experienced locally they process the servereless.yml contents differently than in v2 at some level. I think if you can revert to v2 of the serverless framework it may help avoid this issue.

**Comment by icarus-sullivan** [comment]
@lxandrexl If you're still interested v0.2.0 now supports v3. The api has changed so please take a look at the READMe
