### ISSUE TITLE
Serverless v3 compatibility

### ISSUE THREAD

**Issue by nickjmv** [icarus-sullivan/serverless-plugin-utils#9]
Hi,

I'm having issues getting your plugin to work. The first thing that came to my mind was: does your plugin still work with Serverless v3+? I see this repo has not been updated since May 2021 and after that Serverless v3 was developed.

Thanks in advance for your answer!

**Comment by icarus-sullivan** [comment]
I haven't touched the code in a while, I can update this to use variable resolution but the api for usage will change. I've been pretty busy so haven't pursued this but I can try to spin up a v3 project and test it against variable resolution. 

Ultimately I would need to change the api to operate like the `${file(...)}` helper for serverless. Whether this is possible solely through variable resolution or if a module would need to be automatically imported I haven't dug in quite yet.

**Comment by nickjmv** [comment]
I'm not really following what you are saying as I'm not that experienced/familiar yet with Serverless. But I'll keep following this repo for updates!

**Comment by icarus-sullivan** [comment]
I updated the library to now support v3 of serverless. However, its a an api breaking change so you'll need to take a look at the README.
